# -*- coding: utf-8 -*-
"""wyczytanie_bazy_probek_b_ploszynski.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lrGcVh24UtLMmu0owBhkYrK-AHmLHBES
"""

import urllib.request
import re

def wczytaj_baze_probek_z_tekstem(url_pliku_z_wartosciami, url_pliku_z_opisem_atr):
  try:
    print("wczytaj_baze_probek_z_tekstem function is running")

    response_pliku_z_wartosciami = urllib.request.urlopen(url_pliku_z_wartosciami)
    response_pliku_z_opisem_atr = urllib.request.urlopen(url_pliku_z_opisem_atr)

    plik_z_wartosciami = response_pliku_z_wartosciami.read().decode("utf-8")
    plik_z_opisem_atr = response_pliku_z_opisem_atr.read().decode("utf-8")  

    probki_rows = plik_z_wartosciami.split("\n")
    plik_z_opisem_atr_rows = plik_z_opisem_atr.split("\n")

    probki = []
    attrybuty = []

    for i in range(len(probki_rows)):
      probkiTmp = re.sub(r"\s+", " ", probki_rows[i]).split(" ")

      while("" in probkiTmp): 
        probkiTmp.remove("") 

      probki.append(probkiTmp)

    probki = [x for x in probki if x]

    for i in range(len(plik_z_opisem_atr_rows)):
      attrybutyTmp = re.sub(r"\s+", " ", plik_z_opisem_atr_rows[i]).split(" ")

      while("" in attrybutyTmp): 
        attrybutyTmp.remove("") 

      attrybuty.append(attrybutyTmp)


    czy_atr_symb = []
    nazwy_atr = []

    for atrybut in attrybuty:
      if len(atrybut) < 2: 
        break
      if atrybut[1] == "s":
        czy_atr_symb.append(True)
      else:
        czy_atr_symb.append(False)
      nazwy_atr.append(atrybut[0])
    
    print("probki[0][2]: ", probki[0][2])
    print("probki[1][4]: ", probki[1][4])

    print("czy_atr_symb[0] : ", czy_atr_symb[0] )
    print("czy_atr_symb[1] : ", czy_atr_symb[1] )

    print("nazwy_atr[0] : ", nazwy_atr[0] )
    print("nazwy_atr[1] : ", nazwy_atr[1] )

    print("wczytaj_baze_probek_z_tekstem function has finished")
  except Exception as err:
      exception_type = type(err).__name__
      print("Exception Occureded ", exception_type)
      if exception_type == "HTTPError":
        print("File load exception")

# wczytaj_baze_probek_z_tekstem("http://wmii.uwm.edu.pl/~bnowak/userfiles/downloads/dydaktyka/Systemy_Sztucznej_Inteligencji_Studia_Dzienne/car.txt", "http://wmii.uwm.edu.pl/~bnowak/userfiles/downloads/dydaktyka/Systemy_Sztucznej_Inteligencji_Studia_Dzienne/car-type.txt")
wczytaj_baze_probek_z_tekstem("http://wmii.uwm.edu.pl/~bnowak/userfiles/downloads/dydaktyka/Systemy_Sztucznej_Inteligencji_Studia_Dzienne/iris.txt", "http://wmii.uwm.edu.pl/~bnowak/userfiles/downloads/dydaktyka/Systemy_Sztucznej_Inteligencji_Studia_Dzienne/iris-type.txt")
# wczytaj_baze_probek_z_tekstem("http://wmii.uwm.edu.pl/~bnowak/userfiles/downloads/dydaktyka/Systemy_Sztucznej_Inteligencji_Studia_Dzienne/spirala.txt", "http://wmii.uwm.edu.pl/~bnowak/userfiles/downloads/dydaktyka/Systemy_Sztucznej_Inteligencji_Studia_Dzienne/spirala-type.txt")